imu_sub_topic: /vn100/imu
cam_sub_topic: /cam0/cam0
lidar_sub_topic: /velodyne_points

resize_factor: 1.0
lidar_time_offset_type: zero
ground_truth_file: ""
init_on_ground_truth: false

timeshift_cam_imu: 0.0
imu_g: 9.81
imu_n_gravity_x: 0
imu_n_gravity_y: 0
imu_n_gravity_z: -1
imu_accel_noise_density: 0.001372
imu_gyro_noise_density: 0.00006108
imu_accel_random_walk: 0.00554371716
imu_gyro_random_walk: 0.00068563008

num_good_keyframes_for_initialization: 2
track_nms_squared_dist_thresh: 400.
max_features_per_cell: 7
max_features: 50
grid_cells_x: 9
grid_cells_y: 7
track_count_lower_thresh: 40

min_parallax_for_smoothing: 5
min_parallax_for_smoothing_depth: 0
num_high_parallax_points_for_keyframe: 15
min_track_length_for_smoothing: 40
min_track_length_for_smoothing_depth: 7
min_depth_measurements_for_smoothing: 3
min_active_track_count: 20

use_parallax_keyframes: false
min_parallax_for_keyframe: 20
temporal_keyframe_interval: 30

use_isam: true
isam_relinearize_thresh: 0.1
isam_relinearize_skip: 1
init_range_factor_length: 1.0

noise_params:
  prior_X_yaw: 0.00001
  prior_X_roll_pitch: 0.0001
  prior_X_translation: 0.00001
  prior_gyro: 0.01
  prior_accel: 0.01
  prior_velocity: 0.00001
  between_rotation: 0.001
  between_translation: 0.03
  between_rotation_keyframe: 0.001
  between_translation_keyframe: 0.01
  feature: 1.0
  range: 0.1
  robust_feature_k: 1.345
  robust_range_k: 10

#body_p_cam_quat: [ -0.541994263973, 0.538194367618, -0.457984250078, 0.454796072065 ]
#body_p_cam_vec: [ -0.0321990644814, -0.00236694722335, 0.0596451018445 ]
body_p_cam_quat: [ 0.542799, -0.538632, 0.457321, -0.453985 ]
body_p_cam_vec: [ 0.0330188, 0.00138609, -0.0575828 ]

body_p_imu_quat: [ 0, 0, 0, 1 ]
body_p_imu_vec: [ 0, 0, 0 ]

#body_p_lidar_quat: [ 0, 0, 0, 1 ]
#body_p_lidar_vec: [ 0, 0, 0 ]
body_p_lidar_quat: [ -0.00310895, -0.0073453, -0.00289158, 0.999964 ]
body_p_lidar_vec: [ -0.112588, 0.00132019, 0.0930353 ]

image_width: 720
image_height: 540
cam_fx: 593.690871957
cam_fy: 593.74699226
cam_u0: 388.42480338
cam_v0: 274.84471313
color_image: true

distortion_model:
  coeffs: [ -0.025457951864817117, 0.009902106702461878, -0.043069796963119425, 0.05057305222464838 ]
  type: equidistant

lidar_depth:
  enabled: true
  calc_mode: 1
  search_window_width: 15
  search_window_height: 15
  min_non_zero_neighbors: 4
  max_allowed_feature_distance: 15

lidar_frame_manager_timestamp_thresh: 0.02

dynamic_outlier_rejection_threshold: 15.0
landmark_distance_threshold: 25.
proj_landmark_init_dist_thresh: 25.
extra_isam2_update_steps: 0

use_fixed_lag: true
smoother_lag: 10
enable_smart_factors: false

loam_between_factors_enabled: false
frame_between_factors: false
keyframe_between_factors: false
loam_world_frame: camera_init_CORRECTED
loam_sensor_frame: aft_mapped_to_init_CORRECTED

draw_lidar_lines: true
