count_features_per_cell: false
min_features_per_cell: 3
max_features_per_cell: 10
max_features: 100
grid_cells_x: 9
grid_cells_y: 7
landmark_culling_frame_count: 20
landmark_culling_observation_percentage: .40
landmark_matching_window: 5
match_max_distance: 20.0
init_keyframe_interval: 6
num_good_keyframes_for_initialization: 20
add_essential_matrix_constraints: false
min_keyframe_feature_inlier_ratio: 0.75
min_parallax_for_smoothing: 5
min_parallax_for_smoothing_depth: 0
max_parallax_rotation_compensation: 200
num_high_parallax_points_for_keyframe: 15
min_active_track_count: 20

use_parallax_keyframes: false
min_parallax_for_keyframe: 10
temporal_keyframe_interval: 60
frame_interval: 1

use_isam: true
use_dogleg: false
isam_relinearize_thresh: 0.1
isam_relinearize_skip: 10
save_factor_graphs_to_file: false
init_range_factor_length_: -1.
enable_smart_factors: true
isam_relin_thresh:
  x_rotation: 0.5
  x_translation: 1.0
  v: 0.2
  b: 0.2
  l: 1.0

imu_n_gravity_x: 0
imu_n_gravity_y: 0
imu_n_gravity_z: -9.81

noise_params:
  prior_X_yaw: 0.001
  prior_X_roll_pitch: 0.1
  prior_X_translation: 0.01
  prior_gyro: 0.1
  prior_accel: 0.1
  prior_velocity: 0.1
  between_rotation: 0.001
  between_translation: 0.005
  between_rotation_keyframe: 0.1
  between_translation_keyframe: 0.2
  feature: 1.0
  range: 0.5
  robust_feature_k: 5
  robust_range_k: 5

imu_cam_quat: [ 0, 0, 0, 1 ]
imu_cam_vector: [ 0, 0, 0 ]

body_p_imu_quat: [ 0, 0, 0, 1 ]
body_p_imu_vec: [ 0, 0, 0 ]

body_p_lidar_quat: [ 0, 0, 0, 1 ]
body_p_lidar_vec: [ 0, 0, 0 ]

do_initial_gravity_alignment: false
dynamic_outlier_rejection_threshold: 8.0
landmark_distance_threshold: 30.0
proj_landmark_init_dist_thresh: 6.0
extra_isam2_update_steps: 0

min_keyframes_for_nominal: 20
use_fixed_lag: true
smoother_lag: 10

feature_extraction_interval: 20
track_count_lower_thresh: 50
track_nms_squared_dist_thresh: 1200.
min_track_length_for_smoothing: 5
min_track_length_for_smoothing_depth: 5
min_depth_measurements_for_smoothing: 3
image_edge_padding_percent: .05
stationary_thresh: 0.5

lidar_depth:
  enabled: true
  calc_mode: 0
  search_window_width: 7
  search_window_height: 7
  min_non_zero_neighbors: 10
  max_allowed_feature_distance: 20.
  std_dev_tol_factor: 0.1

draw_lidar_lines: false
