imu_sub_topic: /camera/imu
cam_sub_topic: /camera/infra1/image_rect_raw
lidar_sub_topic: /os1_cloud_node/points

resize_factor: 1.0
ground_truth_file: /home/sigtot/Downloads/data/newer_college/01_short_experiment/ground_truth/registered_poses.csv
lidar_time_offset_file: /home/sigtot/Downloads/data/newer_college/01_short_experiment/time_offsets.csv
ground_truth_provider: newer_college
lidar_time_offset_type: newer_college
init_on_ground_truth: true

timeshift_cam_imu: 0.01379378638037798
imu_g: 9.78961
imu_n_gravity_x: 0
imu_n_gravity_y: 0
imu_n_gravity_z: -1
imu_accel_noise_density: 0.0014715 # m / (s^2 sqrt(Hz))
imu_gyro_noise_density: 0.00174528 # rad / s
imu_accel_random_walk: 0.000106 # Couldn't find in datasheet
imu_gyro_random_walk: 0.000004 # Couldn't find in datasheet

noise_params:
  prior_X_yaw: 0.001
  prior_X_roll_pitch: 0.001
  prior_X_translation: 0.00001
  prior_gyro: 0.1
  prior_accel: 0.1
  prior_velocity: 0.1
  between_rotation: 0.0001
  between_translation: 0.0001
  between_rotation_keyframe: 0.001
  between_translation_keyframe: 0.01
  feature: 1.0
  range: 0.5
  robust_feature_k: 1.345
  robust_range_k: 1.345

use_isam: true
use_dogleg: false
isam_relinearize_thresh: 0.1
isam_relinearize_skip: 1
init_range_factor_length: 1.0

num_good_keyframes_for_initialization: 2
track_nms_squared_dist_thresh: 600.
max_features_per_cell: 3
max_features: 40
grid_cells_x: 9
grid_cells_y: 7
track_count_lower_thresh: 30

min_parallax_for_smoothing: 15
min_parallax_for_smoothing_depth: 0
num_high_parallax_points_for_keyframe: 15
min_track_length_for_smoothing: 20
min_track_length_for_smoothing_depth: 7
min_depth_measurements_for_smoothing: 3
min_active_track_count: 20

use_parallax_keyframes: false
min_parallax_for_keyframe: 20
temporal_keyframe_interval: 30

body_p_cam_quat: [ -0.499321, 0.499958, -0.499171, 0.501547 ]
body_p_cam_vec: [ 0.0159205, 0.00583189, 0.0174204 ]

body_p_imu_quat: [ -0.5, 0.5, -0.5, 0.5 ]
body_p_imu_vec: [ 0, 0, 0 ]

body_p_lidar_quat: [ 0.0122215786, -0.00410931992, 0.923332909, 0.383784484 ]
body_p_lidar_vec: [ -0.0561262623, 0.003222329, 0.00869478206 ]

image_width: 848
image_height: 480
cam_fx: 431.38739114
cam_fy: 430.24961762
cam_u0: 427.4407802
cam_v0: 238.52694868
color_image: false

distortion_model:
  coeffs: [ 0.007925673974579087, -0.0036215088874331737, -0.001422629239660213, 0.0002909310193082525 ]
  type: radtan

lidar_depth:
  enabled: true
  calc_mode: 0
  search_window_width: 15
  search_window_height: 15
  min_non_zero_neighbors: 4
  max_allowed_feature_distance: 30

lidar_frame_manager_timestamp_thresh: 0.02

dynamic_outlier_rejection_threshold: 15.0
landmark_distance_threshold: 15
proj_landmark_init_dist_thresh: 15.0
extra_isam2_update_steps: 0

use_fixed_lag: true
smoother_lag: 10
enable_smart_factors: false

loam_between_factors_enabled: true
frame_between_factors: false
keyframe_between_factors: true
loam_world_frame: camera_init_CORRECTED
loam_sensor_frame: aft_mapped_to_init_CORRECTED
