imu_sub_topic: /camera/imu
cam_sub_topic: /camera/infra1/image_rect_raw

resize_factor: 1.0
ground_truth_file: /home/sigtot/Downloads/data/newer_college/01_short_experiment/ground_truth/registered_poses.csv

timeshift_cam_imu: 0.01379378638037798
imu_g: 9.81
imu_n_gravity_x: 0.11590493
imu_n_gravity_y: -9.80391037
imu_n_gravity_z: -0.32558805
imu_accel_noise_density: 0.001249
imu_gyro_noise_density: 0.000208
imu_accel_random_walk: 0.000106
imu_gyro_random_walk: 0.000004

cam_fx: 431.38739114
cam_fy: 430.24961762
cam_u0: 427.4407802
cam_v0: 238.52694868
