imu_sub_topic: /camera/imu
cam_sub_topic: /camera/infra1/image_rect_raw

resize_factor: 1.0
ground_truth_file: /home/sigtot/Downloads/data/newer_college/01_short_experiment/ground_truth/registered_poses.csv
ground_truth_provider: newer_college
init_on_ground_truth: true

timeshift_cam_imu: 0.01379378638037798
imu_g: 9.81206
imu_n_gravity_x: 0
imu_n_gravity_y: 0
imu_n_gravity_z: -1
imu_accel_noise_density: 0.0014715 # m / (s^2 sqrt(Hz))
imu_gyro_noise_density: 0.00174528 # rad / s
imu_accel_random_walk: 0.000106 # Couldn't find in datasheet
imu_gyro_random_walk: 0.000004 # Couldn't find in datasheet

use_isam: true
use_dogleg: false
isam_relinearize_thresh: 0.1
init_range_factor_length: 8.2

num_good_keyframes_for_initialization: 40
track_nms_squared_dist_thresh: 400.
max_features_per_cell: 6
track_count_lower_thresh: 150

min_parallax_for_keyframe: 15
min_parallax_for_smoothing: 10
num_high_parallax_points_for_keyframe: 30
min_track_length_for_smoothing: 3

body_p_cam_quat: [ -0.5, 0.5, -0.5, 0.5 ]
body_p_cam_vec: [ -0.0442, 0.0173, -0.0158 ]

body_p_imu_quat: [ -0.5, 0.5, -0.5, 0.5 ]
body_p_imu_vec: [ 0, 0, 0 ]

cam_fx: 431.38739114
cam_fy: 430.24961762
cam_u0: 427.4407802
cam_v0: 238.52694868

distortion_model:
  coeffs: [ 0.007925673974579087, -0.0036215088874331737, -0.001422629239660213, 0.0002909310193082525 ]
  type: radtan
